# Generated by Django 4.1.3 on 2022-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_duration_alter_contest_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeredcontestant',
            name='a_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredcontestant',
            name='b_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredcontestant',
            name='c_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registeredcontestant',
            name='d_score',
            field=models.IntegerField(default=0),
        ),
    ]
