# Generated by Django 4.1.3 on 2022-12-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcontestant',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
