# Generated by Django 4.1.3 on 2022-12-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_a_score_alter_contest_b_score_and_more'),
        ('problem', '0003_problem_total_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
    ]
