# Generated by Django 4.1.3 on 2022-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_problem_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='discription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
