# Generated by Django 4.1.3 on 2022-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_submission_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
