# Generated by Django 4.1.3 on 2022-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_submission_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
